name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # This tells GitHub Actions to use a Linux environment for deployment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the Python version you want to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install all dependencies from your requirements.txt
          pip install git+https://github.com/openai/swarm.git  # Install swarm directly from GitHub

      # Step 4: Run your Streamlit app
      - name: Run Streamlit app
        run: |
          streamlit run Advertisement_portfolio.py  # Replace with your main file
